(define (sqrt-newton x)
  (define (good-enough? guess)
    (< (abs (-  (square guess) x)) 0.001))
  (define (average x y)
    (/ (+ x y) 2))
  (define (improve guess)
    (average guess (/ x guess)))
  (define (sqrt-iter guess)
    (if (good-enough? guess)
         guess
         (sqrt-iter (improve guess))))
  (sqrt-iter (/ x 2.0)))
